### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by BurrowIsPog** [Kami147/InstantMine#2]

**Comment by smilingmiko** [comment]
...

**Comment by atnarb** [comment]
if you dont know how to use this you shouldnt be using it ez

**Comment by Tenshi147** [comment]
Just throw it into the client base of your choice and rework the functions to work with that base, this was made to work with [Kami b9 (I can't find the repo lol so here's an old version of Kami Blue)](https://github.com/jenixblue/kami-blue/tree/master)
